<?php

return [
    ['name' => 'Beras Ramos 5 kg', 'category' => 'Sembako', 'price' => 69000, 'description' => 'Beras pulen untuk kebutuhan makan harian keluarga dan stok utama toko.'],
    ['name' => 'Beras Pandan Wangi 5 kg', 'category' => 'Sembako', 'price' => 76000, 'description' => 'Beras wangi dengan tekstur pulen, cocok untuk pelanggan yang mencari kualitas premium.'],
    ['name' => 'Gula Pasir Gulaku 1 kg', 'category' => 'Sembako', 'price' => 17500, 'description' => 'Gula pasir putih untuk minuman, kue, dan kebutuhan dapur sehari-hari.'],
    ['name' => 'Minyak Goreng Bimoli 1 L', 'category' => 'Sembako', 'price' => 20500, 'description' => 'Minyak goreng kemasan satu liter yang praktis untuk kebutuhan rumah tangga.'],
    ['name' => 'Minyak Goreng Tropical 2 L', 'category' => 'Sembako', 'price' => 39000, 'description' => 'Minyak goreng dua liter untuk stok dapur keluarga dan usaha kecil.'],
    ['name' => 'Tepung Terigu Segitiga Biru 1 kg', 'category' => 'Sembako', 'price' => 15000, 'description' => 'Tepung serbaguna untuk membuat gorengan, kue, roti, dan adonan rumahan.'],
    ['name' => 'Tepung Tapioka Pak Tani 500 g', 'category' => 'Sembako', 'price' => 9000, 'description' => 'Tepung tapioka untuk cilok, cireng, pempek, dan aneka jajanan kenyal.'],
    ['name' => 'Telur Ayam Negeri 1 kg', 'category' => 'Sembako', 'price' => 31000, 'description' => 'Telur ayam segar untuk lauk, kue, dan kebutuhan sarapan keluarga.'],
    ['name' => 'Mie Sedaap Goreng 90 g', 'category' => 'Sembako', 'price' => 3500, 'description' => 'Mie instan goreng rasa gurih yang cepat disajikan dan banyak dicari pembeli.'],
    ['name' => 'Indomie Goreng 85 g', 'category' => 'Sembako', 'price' => 3600, 'description' => 'Mie instan goreng favorit untuk stok warung, kos, dan rumah.'],
    ['name' => 'Indomie Soto Mie 70 g', 'category' => 'Sembako', 'price' => 3400, 'description' => 'Mie kuah rasa soto yang ringan untuk makan cepat saat hujan atau malam hari.'],
    ['name' => 'Garam Meja Cap Kapal 250 g', 'category' => 'Sembako', 'price' => 4500, 'description' => 'Garam meja halus untuk masakan harian dan pelengkap dapur.'],
    ['name' => 'Kecap Manis ABC 600 ml', 'category' => 'Sembako', 'price' => 27000, 'description' => 'Kecap manis kental untuk tumisan, nasi goreng, sate, dan lauk rumahan.'],
    ['name' => 'Saus Sambal ABC 335 ml', 'category' => 'Sembako', 'price' => 15500, 'description' => 'Saus sambal botol untuk pelengkap gorengan, mie, bakso, dan camilan.'],
    ['name' => 'Saus Tomat Indofood 340 ml', 'category' => 'Sembako', 'price' => 15000, 'description' => 'Saus tomat dengan rasa manis asam untuk kentang goreng, sosis, dan masakan.'],
    ['name' => 'Santan Kara 65 ml', 'category' => 'Sembako', 'price' => 4500, 'description' => 'Santan instan kecil untuk opor, rendang, gulai, dan kolak.'],
    ['name' => 'Susu Kental Manis Frisian Flag 370 g', 'category' => 'Sembako', 'price' => 13500, 'description' => 'Susu kental manis kaleng untuk roti, minuman, martabak, dan dessert.'],
    ['name' => 'Kopi Kapal Api Special Mix 10 sachet', 'category' => 'Sembako', 'price' => 15500, 'description' => 'Kopi sachet praktis untuk stok meja kasir, rumah, dan kantor kecil.'],
    ['name' => 'Teh Celup SariWangi 25 kantong', 'category' => 'Sembako', 'price' => 14500, 'description' => 'Teh celup harum untuk minuman pagi, tamu, atau sajian hangat keluarga.'],
    ['name' => 'Margarin Blue Band 200 g', 'category' => 'Sembako', 'price' => 12000, 'description' => 'Margarin untuk roti bakar, tumisan, kue, dan masakan rumahan.'],
    ['name' => 'Kornet Pronas 198 g', 'category' => 'Sembako', 'price' => 24500, 'description' => 'Kornet kaleng praktis untuk nasi goreng, roti isi, dan lauk cepat saji.'],
    ['name' => 'Sarden ABC Saus Tomat 155 g', 'category' => 'Sembako', 'price' => 11000, 'description' => 'Sarden kaleng dengan saus tomat untuk lauk cepat dan stok darurat.'],
    ['name' => 'Bihun Jagung Padamu 320 g', 'category' => 'Sembako', 'price' => 12500, 'description' => 'Bihun jagung untuk sop, bihun goreng, soto, dan menu rumahan.'],
    ['name' => 'Kacang Hijau Kupas 500 g', 'category' => 'Sembako', 'price' => 18000, 'description' => 'Kacang hijau untuk bubur, isian kue, dan minuman hangat.'],
    ['name' => 'Bumbu Racik Ayam Goreng Indofood', 'category' => 'Sembako', 'price' => 3000, 'description' => 'Bumbu instan ayam goreng yang praktis untuk memasak lauk harian.'],
    ['name' => 'Bumbu Racik Sayur Sop Indofood', 'category' => 'Sembako', 'price' => 3000, 'description' => 'Bumbu sop instan untuk kuah sayur yang gurih dan cepat dibuat.'],
    ['name' => 'Masako Ayam 100 g', 'category' => 'Sembako', 'price' => 6500, 'description' => 'Penyedap rasa ayam untuk masakan tumis, sup, dan gorengan.'],
    ['name' => 'Ladaku Merica Bubuk 35 g', 'category' => 'Sembako', 'price' => 10500, 'description' => 'Merica bubuk untuk menambah aroma dan rasa hangat pada masakan.'],
    ['name' => 'Bawang Goreng Kemasan 100 g', 'category' => 'Sembako', 'price' => 16000, 'description' => 'Bawang goreng renyah untuk taburan nasi, soto, mie, dan bubur.'],
    ['name' => 'Kerupuk Udang Finna 250 g', 'category' => 'Sembako', 'price' => 17000, 'description' => 'Kerupuk udang mentah untuk pelengkap makan keluarga dan stok warung.'],
    ['name' => 'Aqua Air Mineral 600 ml', 'category' => 'Minuman', 'price' => 4500, 'description' => 'Air mineral botol ukuran sedang untuk pelanggan yang butuh minum cepat.'],
    ['name' => 'Aqua Air Mineral 1.5 L', 'category' => 'Minuman', 'price' => 7500, 'description' => 'Air mineral botol besar untuk bekal perjalanan dan stok rumah.'],
    ['name' => 'Le Minerale 600 ml', 'category' => 'Minuman', 'price' => 4300, 'description' => 'Air mineral botol praktis dengan rasa segar untuk aktivitas harian.'],
    ['name' => 'Teh Botol Sosro 350 ml', 'category' => 'Minuman', 'price' => 6500, 'description' => 'Teh siap minum rasa manis segar untuk menemani makan siang.'],
    ['name' => 'Fruit Tea Blackcurrant 350 ml', 'category' => 'Minuman', 'price' => 6500, 'description' => 'Teh rasa buah blackcurrant yang cocok untuk stok minuman dingin.'],
    ['name' => 'Ultra Milk Cokelat 250 ml', 'category' => 'Minuman', 'price' => 7000, 'description' => 'Susu UHT rasa cokelat untuk bekal sekolah dan minuman anak.'],
    ['name' => 'Ultra Milk Stroberi 250 ml', 'category' => 'Minuman', 'price' => 7000, 'description' => 'Susu UHT rasa stroberi dengan kemasan kecil yang mudah dibawa.'],
    ['name' => 'Milo Activ-Go 240 ml', 'category' => 'Minuman', 'price' => 8500, 'description' => 'Minuman cokelat malt siap minum untuk tambahan energi harian.'],
    ['name' => 'Pocari Sweat 500 ml', 'category' => 'Minuman', 'price' => 8500, 'description' => 'Minuman isotonik untuk mengganti cairan tubuh setelah beraktivitas.'],
    ['name' => 'You C1000 Lemon 140 ml', 'category' => 'Minuman', 'price' => 9500, 'description' => 'Minuman vitamin C rasa lemon untuk pelanggan yang ingin minuman segar.'],
    ['name' => 'Yakult 5 botol', 'category' => 'Minuman', 'price' => 11500, 'description' => 'Minuman probiotik kecil untuk stok kulkas keluarga.'],
    ['name' => 'Good Day Cappuccino 250 ml', 'category' => 'Minuman', 'price' => 7500, 'description' => 'Kopi susu kemasan dengan rasa cappuccino yang manis dan ringan.'],
    ['name' => 'Nescafe Latte Can 220 ml', 'category' => 'Minuman', 'price' => 10500, 'description' => 'Kopi latte kaleng untuk pelanggan yang ingin kopi dingin praktis.'],
    ['name' => 'Floridina Orange 350 ml', 'category' => 'Minuman', 'price' => 4500, 'description' => 'Minuman jeruk dengan bulir buah yang segar diminum dingin.'],
    ['name' => 'Pulpy Orange 300 ml', 'category' => 'Minuman', 'price' => 7500, 'description' => 'Minuman jeruk dengan pulp buah untuk pilihan minuman siang hari.'],
    ['name' => 'Coca-Cola 390 ml', 'category' => 'Minuman', 'price' => 6500, 'description' => 'Minuman bersoda kemasan botol untuk acara santai dan makan bersama.'],
    ['name' => 'Sprite 390 ml', 'category' => 'Minuman', 'price' => 6500, 'description' => 'Soda lemon lime yang segar untuk stok minuman dingin toko.'],
    ['name' => 'Fanta Stroberi 390 ml', 'category' => 'Minuman', 'price' => 6500, 'description' => 'Minuman soda rasa stroberi dengan warna menarik dan rasa manis.'],
    ['name' => 'Indomilk Kids Cokelat 115 ml', 'category' => 'Minuman', 'price' => 3500, 'description' => 'Susu kecil rasa cokelat untuk jajanan anak dan bekal sekolah.'],
    ['name' => 'Teh Pucuk Harum 350 ml', 'category' => 'Minuman', 'price' => 5000, 'description' => 'Teh melati siap minum dengan rasa manis yang ringan.'],
    ['name' => 'Golda Coffee Dolce Latte 200 ml', 'category' => 'Minuman', 'price' => 4500, 'description' => 'Kopi susu botol kecil dengan rasa manis creamy yang populer.'],
    ['name' => 'Bear Brand Susu Steril 189 ml', 'category' => 'Minuman', 'price' => 11500, 'description' => 'Susu steril kaleng untuk pelanggan yang mencari minuman bernutrisi.'],
    ['name' => 'Larutan Cap Kaki Tiga 320 ml', 'category' => 'Minuman', 'price' => 8500, 'description' => 'Minuman larutan penyegar untuk stok kebutuhan harian keluarga.'],
    ['name' => 'Nutrisari Jeruk Sachet', 'category' => 'Minuman', 'price' => 2000, 'description' => 'Minuman serbuk rasa jeruk yang mudah diseduh dengan air dingin.'],
    ['name' => 'Chocolatos Drink Cokelat Sachet', 'category' => 'Minuman', 'price' => 2500, 'description' => 'Minuman cokelat sachet untuk diseduh panas atau dingin.'],
    ['name' => 'Chitato Sapi Panggang 68 g', 'category' => 'Snack', 'price' => 11500, 'description' => 'Keripik kentang rasa sapi panggang untuk camilan santai.'],
    ['name' => 'Lays Rumput Laut 68 g', 'category' => 'Snack', 'price' => 11500, 'description' => 'Keripik kentang rasa rumput laut yang gurih dan ringan.'],
    ['name' => 'Qtela Singkong Balado 60 g', 'category' => 'Snack', 'price' => 8500, 'description' => 'Keripik singkong rasa balado pedas manis untuk teman nonton.'],
    ['name' => 'Taro Net Seaweed 65 g', 'category' => 'Snack', 'price' => 9500, 'description' => 'Snack jaring rasa rumput laut yang renyah dan disukai anak-anak.'],
    ['name' => 'Beng-Beng Share It 95 g', 'category' => 'Snack', 'price' => 10500, 'description' => 'Wafer cokelat isi beberapa potong untuk dibagi bersama teman.'],
    ['name' => 'SilverQueen Chunky Bar 100 g', 'category' => 'Snack', 'price' => 23000, 'description' => 'Cokelat kacang mede ukuran besar untuk hadiah kecil atau camilan.'],
    ['name' => 'Delfi Twister Black 80 g', 'category' => 'Snack', 'price' => 9000, 'description' => 'Wafer roll cokelat yang renyah untuk camilan sore.'],
    ['name' => 'Oreo Original 133 g', 'category' => 'Snack', 'price' => 10500, 'description' => 'Biskuit cokelat krim vanilla untuk camilan keluarga.'],
    ['name' => 'Roma Kelapa 300 g', 'category' => 'Snack', 'price' => 12000, 'description' => 'Biskuit kelapa klasik yang cocok untuk teman teh atau kopi.'],
    ['name' => 'Khong Guan Assorted 650 g', 'category' => 'Snack', 'price' => 58000, 'description' => 'Biskuit kaleng campur untuk suguhan tamu dan stok hari raya.'],
    ['name' => 'Good Time Chocochips 72 g', 'category' => 'Snack', 'price' => 9000, 'description' => 'Cookies chocochips renyah untuk bekal dan camilan ringan.'],
    ['name' => 'Nabati Richeese Wafer 145 g', 'category' => 'Snack', 'price' => 9500, 'description' => 'Wafer krim keju dengan rasa gurih manis yang mudah laku.'],
    ['name' => 'Tango Wafer Vanilla 130 g', 'category' => 'Snack', 'price' => 10000, 'description' => 'Wafer rasa vanilla dengan lapisan renyah untuk camilan harian.'],
    ['name' => 'Momogi Jagung Bakar 50 g', 'category' => 'Snack', 'price' => 5500, 'description' => 'Snack jagung rasa bakar yang ringan untuk jajanan anak.'],
    ['name' => 'Kusuka Keripik Singkong Original 60 g', 'category' => 'Snack', 'price' => 8000, 'description' => 'Keripik singkong original yang gurih dan cocok untuk teman makan.'],
    ['name' => 'Garuda Kacang Kulit 250 g', 'category' => 'Snack', 'price' => 21000, 'description' => 'Kacang kulit panggang untuk camilan keluarga dan acara santai.'],
    ['name' => 'Dua Kelinci Kacang Sukro 140 g', 'category' => 'Snack', 'price' => 13500, 'description' => 'Kacang bersalut tepung renyah dengan rasa gurih yang khas.'],
    ['name' => 'Kinder Joy Boys 20 g', 'category' => 'Snack', 'price' => 14500, 'description' => 'Cokelat dan mainan kecil yang sering dicari anak-anak.'],
    ['name' => 'Pocky Cokelat 47 g', 'category' => 'Snack', 'price' => 9500, 'description' => 'Biskuit stik berlapis cokelat untuk camilan praktis.'],
    ['name' => 'Malkist Roma Cokelat 135 g', 'category' => 'Snack', 'price' => 8500, 'description' => 'Malkist berlapis cokelat untuk teman minum teh.'],
    ['name' => 'Roti Tawar Sari Roti Kupas', 'category' => 'Snack', 'price' => 18000, 'description' => 'Roti tawar kupas yang lembut untuk sarapan dan bekal.'],
    ['name' => 'Roti Sobek Cokelat Sari Roti', 'category' => 'Snack', 'price' => 17500, 'description' => 'Roti sobek isi cokelat yang cocok untuk camilan keluarga.'],
    ['name' => 'Kue Bolu Pandan Mini', 'category' => 'Snack', 'price' => 7000, 'description' => 'Bolu pandan kecil dengan aroma wangi untuk jajanan cepat.'],
    ['name' => 'Donat Gula Halus Isi 6', 'category' => 'Snack', 'price' => 22000, 'description' => 'Donat empuk bertabur gula halus untuk sarapan atau bekal.'],
    ['name' => 'Kacang Atom Garuda 100 g', 'category' => 'Snack', 'price' => 10500, 'description' => 'Kacang atom renyah untuk camilan sambil bekerja atau belajar.'],
    ['name' => 'Pilus Garuda Pedas 95 g', 'category' => 'Snack', 'price' => 9000, 'description' => 'Pilus rasa pedas gurih untuk camilan ringan yang nagih.'],
    ['name' => 'Permen Kopiko 150 g', 'category' => 'Snack', 'price' => 12500, 'description' => 'Permen rasa kopi untuk stok meja kasir dan suguhan kecil.'],
    ['name' => 'Permen Relaxa Barley Mint 125 g', 'category' => 'Snack', 'price' => 11500, 'description' => 'Permen mint segar untuk menghilangkan rasa tidak nyaman di mulut.'],
    ['name' => 'Yupi Gummy Pizza 120 g', 'category' => 'Snack', 'price' => 16000, 'description' => 'Permen jelly warna-warni yang menarik untuk anak-anak.'],
    ['name' => 'Es Krim Aice Chocolate Crispy', 'category' => 'Snack', 'price' => 5000, 'description' => 'Es krim cokelat renyah untuk stok freezer toko.'],
    ['name' => 'Rinso Deterjen Bubuk 770 g', 'category' => 'Kebersihan', 'price' => 23000, 'description' => 'Deterjen bubuk untuk mencuci pakaian harian dengan busa cukup banyak.'],
    ['name' => 'Daia Deterjen Bubuk 850 g', 'category' => 'Kebersihan', 'price' => 21000, 'description' => 'Deterjen ekonomis untuk kebutuhan cuci pakaian keluarga.'],
    ['name' => 'So Klin Liquid 800 ml', 'category' => 'Kebersihan', 'price' => 18500, 'description' => 'Deterjen cair untuk mencuci pakaian agar lebih mudah larut.'],
    ['name' => 'Molto Pewangi Pakaian 800 ml', 'category' => 'Kebersihan', 'price' => 17500, 'description' => 'Pewangi dan pelembut pakaian untuk hasil cucian yang harum.'],
    ['name' => 'Downy Passion 720 ml', 'category' => 'Kebersihan', 'price' => 28500, 'description' => 'Pelembut pakaian dengan wangi tahan lama untuk cucian keluarga.'],
    ['name' => 'Sunlight Jeruk Nipis 755 ml', 'category' => 'Kebersihan', 'price' => 18500, 'description' => 'Sabun cuci piring aroma jeruk nipis untuk membersihkan lemak.'],
    ['name' => 'Mama Lemon 780 ml', 'category' => 'Kebersihan', 'price' => 17000, 'description' => 'Sabun cuci piring cair yang efektif untuk piring berminyak.'],
    ['name' => 'Wipol Karbol Cemara 780 ml', 'category' => 'Kebersihan', 'price' => 20500, 'description' => 'Karbol pembersih lantai untuk menjaga rumah tetap bersih dan wangi.'],
    ['name' => 'Super Pell Lemon 770 ml', 'category' => 'Kebersihan', 'price' => 15000, 'description' => 'Pembersih lantai aroma lemon untuk dipakai setiap hari.'],
    ['name' => 'Baygon Aerosol 600 ml', 'category' => 'Kebersihan', 'price' => 39000, 'description' => 'Obat nyamuk semprot untuk membantu mengurangi nyamuk di ruangan.'],
    ['name' => 'HIT Elektrik Refill 45 ml', 'category' => 'Kebersihan', 'price' => 18500, 'description' => 'Isi ulang obat nyamuk elektrik untuk perlindungan malam hari.'],
    ['name' => 'Kapur Barus Swallow 150 g', 'category' => 'Kebersihan', 'price' => 12000, 'description' => 'Kapur barus untuk lemari pakaian, kamar mandi, dan gudang kecil.'],
    ['name' => 'Tisu Paseo Smart 250 lembar', 'category' => 'Kebersihan', 'price' => 16000, 'description' => 'Tisu wajah lembut untuk meja makan, kamar, dan kebutuhan harian.'],
    ['name' => 'Tisu Toilet Nice 10 roll', 'category' => 'Kebersihan', 'price' => 36000, 'description' => 'Tisu toilet isi banyak untuk stok kamar mandi rumah.'],
    ['name' => 'Plastik Sampah Hitam 60x80', 'category' => 'Kebersihan', 'price' => 18000, 'description' => 'Kantong sampah ukuran sedang untuk rumah, toko, dan kantor kecil.'],
    ['name' => 'Sapu Lidi Gagang Panjang', 'category' => 'Kebersihan', 'price' => 17000, 'description' => 'Sapu lidi untuk membersihkan halaman dan area depan toko.'],
    ['name' => 'Sikat Lantai Nagata', 'category' => 'Kebersihan', 'price' => 14500, 'description' => 'Sikat lantai kuat untuk membersihkan kamar mandi dan noda membandel.'],
    ['name' => 'Spon Cuci Piring Scotch-Brite', 'category' => 'Kebersihan', 'price' => 9000, 'description' => 'Spon cuci piring dua sisi untuk membersihkan alat makan dan panci.'],
    ['name' => 'Sarung Tangan Karet King', 'category' => 'Kebersihan', 'price' => 13000, 'description' => 'Sarung tangan karet untuk mencuci piring dan membersihkan rumah.'],
    ['name' => 'Pengharum Ruangan Stella Jeruk', 'category' => 'Kebersihan', 'price' => 15500, 'description' => 'Pengharum ruangan aroma jeruk untuk kamar, toko, dan ruang tamu.'],
    ['name' => 'Lifebuoy Sabun Batang Total 10', 'category' => 'Perawatan', 'price' => 5500, 'description' => 'Sabun mandi batang antibakteri untuk kebutuhan mandi harian.'],
    ['name' => 'Dettol Sabun Batang Original', 'category' => 'Perawatan', 'price' => 8500, 'description' => 'Sabun antiseptik untuk membantu menjaga kebersihan kulit.'],
    ['name' => 'Lux Body Wash Soft Rose 450 ml', 'category' => 'Perawatan', 'price' => 34000, 'description' => 'Sabun cair mandi aroma bunga untuk kulit terasa segar dan harum.'],
    ['name' => 'Citra Handbody Bengkoang 230 ml', 'category' => 'Perawatan', 'price' => 24500, 'description' => 'Lotion tubuh bengkoang untuk melembapkan kulit setelah mandi.'],
    ['name' => 'Vaseline Healthy Bright 200 ml', 'category' => 'Perawatan', 'price' => 32000, 'description' => 'Body lotion untuk menjaga kelembapan kulit saat aktivitas harian.'],
    ['name' => 'Pepsodent Pasta Gigi 190 g', 'category' => 'Perawatan', 'price' => 17500, 'description' => 'Pasta gigi keluarga untuk membersihkan gigi dan menyegarkan napas.'],
    ['name' => 'Closeup Menthol Fresh 160 g', 'category' => 'Perawatan', 'price' => 18000, 'description' => 'Pasta gigi gel rasa menthol untuk napas terasa lebih segar.'],
    ['name' => 'Sikat Gigi Formula Medium', 'category' => 'Perawatan', 'price' => 9000, 'description' => 'Sikat gigi bulu medium untuk membersihkan gigi setiap hari.'],
    ['name' => 'Shampoo Sunsilk Black Shine 170 ml', 'category' => 'Perawatan', 'price' => 23000, 'description' => 'Shampoo untuk rambut hitam agar tampak bersih dan berkilau.'],
    ['name' => 'Shampoo Clear Men Cool Sport 160 ml', 'category' => 'Perawatan', 'price' => 25500, 'description' => 'Shampoo pria dengan sensasi dingin setelah keramas.'],
    ['name' => 'Pantene Conditioner 160 ml', 'category' => 'Perawatan', 'price' => 28500, 'description' => 'Conditioner untuk membantu rambut terasa lebih halus dan mudah diatur.'],
    ['name' => 'Rexona Roll On Women 45 ml', 'category' => 'Perawatan', 'price' => 18000, 'description' => 'Deodoran roll on wanita untuk menjaga tubuh tetap percaya diri.'],
    ['name' => 'Rexona Roll On Men 45 ml', 'category' => 'Perawatan', 'price' => 18000, 'description' => 'Deodoran roll on pria untuk aktivitas harian yang padat.'],
    ['name' => 'Garnier Micellar Water 125 ml', 'category' => 'Perawatan', 'price' => 33000, 'description' => 'Pembersih wajah untuk mengangkat makeup ringan dan kotoran.'],
    ['name' => 'Ponds Bright Beauty Facial Foam 100 g', 'category' => 'Perawatan', 'price' => 26500, 'description' => 'Sabun cuci muka untuk membersihkan wajah dari minyak dan debu.'],
    ['name' => 'Kapas Selection 75 g', 'category' => 'Perawatan', 'price' => 9500, 'description' => 'Kapas lembut untuk membersihkan wajah, luka ringan, dan kebutuhan bayi.'],
    ['name' => 'Softex Daun Sirih 23 cm', 'category' => 'Perawatan', 'price' => 16500, 'description' => 'Pembalut wanita ukuran reguler untuk kebutuhan bulanan.'],
    ['name' => 'Sweety Baby Diapers M 20', 'category' => 'Perawatan', 'price' => 52000, 'description' => 'Popok bayi ukuran M untuk menjaga bayi tetap nyaman dan kering.'],
    ['name' => 'Zwitsal Baby Bath 200 ml', 'category' => 'Perawatan', 'price' => 23500, 'description' => 'Sabun mandi bayi dengan wangi lembut untuk kulit sensitif.'],
    ['name' => 'Minyak Kayu Putih Cap Lang 120 ml', 'category' => 'Perawatan', 'price' => 42000, 'description' => 'Minyak kayu putih untuk menghangatkan tubuh dan meredakan masuk angin ringan.'],
    ['name' => 'Sosis So Nice Ayam 375 g', 'category' => 'Frozen', 'price' => 29500, 'description' => 'Sosis ayam beku untuk sarapan, bekal, dan lauk cepat saji.'],
    ['name' => 'Nugget Fiesta Chicken 500 g', 'category' => 'Frozen', 'price' => 59000, 'description' => 'Nugget ayam beku yang praktis digoreng untuk menu anak.'],
    ['name' => 'Bakso Sapi Bernardi 250 g', 'category' => 'Frozen', 'price' => 36000, 'description' => 'Bakso sapi beku untuk sop, mie kuah, dan bakso rumahan.'],
    ['name' => 'Kentang Goreng Mydibel 1 kg', 'category' => 'Frozen', 'price' => 42000, 'description' => 'Kentang beku siap goreng untuk camilan dan pelengkap makanan.'],
    ['name' => 'Otak-Otak Ikan Minaku 500 g', 'category' => 'Frozen', 'price' => 33000, 'description' => 'Otak-otak ikan beku untuk digoreng sebagai camilan gurih.'],
    ['name' => 'Dimsum Ayam Isi 10', 'category' => 'Frozen', 'price' => 38000, 'description' => 'Dimsum ayam beku yang bisa dikukus untuk sajian cepat.'],
    ['name' => 'Kaki Naga Ikan 500 g', 'category' => 'Frozen', 'price' => 31000, 'description' => 'Olahan ikan beku untuk lauk praktis dan bekal anak.'],
    ['name' => 'Cireng Isi Ayam Suwir 10 pcs', 'category' => 'Frozen', 'price' => 26000, 'description' => 'Cireng isi pedas gurih yang cocok untuk camilan sore.'],
    ['name' => 'Roti Maryam Original 5 pcs', 'category' => 'Frozen', 'price' => 24000, 'description' => 'Roti maryam beku untuk dipanaskan dengan topping manis atau gurih.'],
    ['name' => 'Donat Kentang Beku 10 pcs', 'category' => 'Frozen', 'price' => 35000, 'description' => 'Donat kentang beku yang siap digoreng dan diberi topping.'],
    ['name' => 'Ayam Ungkep Kuning 500 g', 'category' => 'Frozen', 'price' => 45000, 'description' => 'Ayam berbumbu kuning siap goreng untuk lauk keluarga.'],
    ['name' => 'Cedea Fish Dumpling Cheese 200 g', 'category' => 'Frozen', 'price' => 27000, 'description' => 'Dumpling ikan isi keju untuk steamboat, sup, atau gorengan.'],
    ['name' => 'Kulit Pangsit Beku 250 g', 'category' => 'Frozen', 'price' => 18000, 'description' => 'Kulit pangsit siap pakai untuk siomay, pangsit goreng, dan dimsum.'],
    ['name' => 'Edamame Beku 500 g', 'category' => 'Frozen', 'price' => 31000, 'description' => 'Edamame beku untuk camilan sehat setelah direbus sebentar.'],
    ['name' => 'Sayur Mix Beku 500 g', 'category' => 'Frozen', 'price' => 22000, 'description' => 'Campuran wortel, jagung, dan buncis beku untuk sup dan tumisan.'],
    ['name' => 'Buku Tulis Sinar Dunia 38 Lembar', 'category' => 'Perlengkapan', 'price' => 4500, 'description' => 'Buku tulis standar untuk sekolah, catatan toko, dan kebutuhan harian.'],
    ['name' => 'Pulpen Standard AE7 Hitam', 'category' => 'Perlengkapan', 'price' => 3500, 'description' => 'Pulpen tinta hitam untuk menulis nota, daftar belanja, dan pekerjaan sekolah.'],
    ['name' => 'Pensil 2B Faber-Castell', 'category' => 'Perlengkapan', 'price' => 4000, 'description' => 'Pensil 2B untuk ujian, menggambar, dan kebutuhan tulis harian.'],
    ['name' => 'Penghapus Staedtler Kecil', 'category' => 'Perlengkapan', 'price' => 3000, 'description' => 'Penghapus kecil yang mudah dibawa di tempat pensil anak sekolah.'],
    ['name' => 'Lakban Bening 2 Inch', 'category' => 'Perlengkapan', 'price' => 12000, 'description' => 'Lakban bening lebar untuk packing paket dan kebutuhan toko.'],
    ['name' => 'Amplop Cokelat A4 Isi 10', 'category' => 'Perlengkapan', 'price' => 15000, 'description' => 'Amplop cokelat ukuran A4 untuk dokumen sekolah, kantor, dan administrasi toko.'],
    ['name' => 'Kertas HVS A4 70 gsm 500 Lembar', 'category' => 'Perlengkapan', 'price' => 52000, 'description' => 'Kertas HVS untuk mencetak laporan, nota, tugas sekolah, dan arsip toko.'],
    ['name' => 'Baterai ABC AA Isi 4', 'category' => 'Perlengkapan', 'price' => 17000, 'description' => 'Baterai ukuran AA untuk remote, jam dinding, mainan, dan senter kecil.'],
    ['name' => 'Korek Api Gas Tokai', 'category' => 'Perlengkapan', 'price' => 4500, 'description' => 'Korek api gas praktis untuk dapur, lilin, dan kebutuhan rumah tangga.'],
    ['name' => 'Payung Lipat Hitam', 'category' => 'Perlengkapan', 'price' => 38000, 'description' => 'Payung lipat ringkas untuk stok musim hujan dan kebutuhan perjalanan.'],
];
